/*
 * This source file was generated by the Gradle 'init' task
 */
package ticket.booking;


import ticket.booking.entities.User;
import ticket.booking.services.TrainService;
import ticket.booking.services.UserBookingService;
import ticket.booking.utils.UserServiceUtil;

import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.stream.Collectors;


public class App {

    public static void main(String[] args) throws IOException {

        System.out.println("Booking System: ");
        Scanner scanner = new Scanner(System.in);

        UserBookingService userBookingService;
        try {
            userBookingService = new UserBookingService();
        } catch (IOException e) {
            System.out.println(e + "IOException occuring");
            return;
        }

        TrainService trainService;
        try {
            trainService = new TrainService();
        } catch (IOException e) {
            System.out.println(e + "Trains IOEXCEPTION ");
            return;
        }
        int option = 0;

        while (option != 7) {
            System.out.println("Choose option");
            System.out.println("1. Sign up");
            System.out.println("2. Login");
            System.out.println("3. Fetch Bookings");
            System.out.println("4. Search Trains");
            System.out.println("5. Book a Seat");
            System.out.println("6. Cancel my Booking");
            System.out.println("7. Exit the App");

            if (!scanner.hasNextInt()) {
                System.out.println("Invalid input. Please enter a number between 1 and 7.");
                scanner.nextLine(); // clear invalid input
                continue;
            }

            option = scanner.nextInt();
            scanner.nextLine();

            switch (option) {
                case 1:
                    System.out.println("Enter username to signup: ");
                    String userNameSignUp = scanner.nextLine();
                    System.out.println("Enter Age:  ");
                    String ageSignUp = scanner.nextLine();
                    System.out.println("Enter sex: ");
                    String sexSignUp = scanner.nextLine();
                    System.out.println("Enter password: ");
                    String passwordSignUp = scanner.nextLine();

                    User userToSignUp = new User(UUID.randomUUID().toString(), userNameSignUp, ageSignUp, sexSignUp, passwordSignUp, UserServiceUtil.hashPassword(passwordSignUp), new ArrayList<>());
                    userBookingService.signUp(userToSignUp);
                    break;

                case 2:
                    System.out.println("Enter username to login: ");
                    String userNameLogin = scanner.nextLine();
                    System.out.println("Enter password: ");
                    String passwordLogin = scanner.nextLine();

                    Optional<User> loggedInUser = userBookingService.loginUser(userNameLogin, passwordLogin);

                    if (loggedInUser.isPresent()) {
                        System.out.println("Login successful for: " + loggedInUser.get().getUserName());
                    } else {
                        System.out.println("Invalid username or password!");
                    }
                    break;

                case 3:
                    System.out.println("Fetching Bookings: ");
                    userBookingService.fetchBooking();
                    break;

                case 4:
                    System.out.println("Enter source station: ");
                    String sourceStation = scanner.nextLine();
                    System.out.println("Enter destination station");
                    String destinationStation = scanner.nextLine();

                    trainService.getTrains(sourceStation, destinationStation);

                case 5:
                    if (userBookingService.checkLoggedInUser()) {

                        System.out.println("Enter source station: ");
                        String sourceStation1 = scanner.nextLine();
                        System.out.println("Enter destination station");
                        String destinationStation1 = scanner.nextLine();
                        userBookingService.bookTickets(sourceStation1, destinationStation1);

                    } else {
                        System.out.println("Please login first");
                    }
                    break;

                case 6:

                    if(userBookingService.checkLoggedInUser()){
                       String ticketID = userBookingService.fetchBookingCheck();
                       userBookingService.cancelTicket(ticketID);
                    }else{
                        System.out.println("login please::");
                    }

                    break;

                //get tickets booked. --> fetchbooking
                //select which ticket to cancel  -> loop over and select the number.
                //update the users.json(ticketbooked based on ID) as well as trains.json(based on seat)
            }
        }

    }
}
